### PR TITLE
Unlock on enter

### LINKED ISSUE #181: Unlock via enter key
- [ ] unlock pop up submits via enter key

### PR DESCRIPTION
**Pull request by gotjoshua**
closes #181

### CODE REVIEW

**Comment by jhlx** [comment]
Hey, can you make a new branch forked from master (rather than forked from in_memory_wallet_unlock) with these changes?

**Comment by gotjoshua** [comment]
> a new branch forked from master

https://github.com/project-serum/spl-token-wallet/pull/187

**Comment by gotjoshua** [comment]
@jhlx  which style do you prefer?

https://github.com/project-serum/spl-token-wallet/pull/182/commits/fb4b5e3110e10d425fd6a8d5919661bf22530465

**Comment by jhlx** [comment]
Ah we should use the other PR, since that one is branched from master.

**Pull request closed without merging**
