### PR TITLE
Where should issues be filed?

### PR DESCRIPTION
**Pull request by tredondo**
The Issues tab is obviously missing. Can the README be updated to say if there's another issue tracker, or if the project is no longer maintained?

### CODE REVIEW

**Comment by armaniferrante** [comment]
The project is not being actively maintained. There is no alternative tracker.

**Comment by tredondo** [comment]
Wow!

Don't you think that's important enough to be mentioned not only in the README, but as a notice in that welcome popup that only says it's a wallet for developers?

People are storing real MONEY in this software.

**Comment by armaniferrante** [comment]
To be clear, support requests are taken and responded to in Discord. However, the maintainers have been pushing the ecosystem to newer wallets like Phantom and Solflare for quite some time now. New feature requests and general maintenance for miscellaneous, non security related, requests are not entertained.

**Comment by tredondo** [comment]
Got it. I landed on this repo via the "View source" link on Sollet. I don't see any link to Discord there. Would it make to sense add one?

To reiterate on my questions:

1. Would it help users to specify in that welcome popup the state of the project? The way I read it is that Sollet is more developer-friendly; not that it won't be maintained any more. IMO, that popup misleads users into hoping that, as with most other projects, new features and general maintenance *are* likely to be implemented.

2. Would it make sense to specify in the README of this project, its state, as the vast majority of open-source projects on GitHub do? You have thousands of commits; it's not like you're new to GitHub. I'm really puzzled by the lack of clarity here.

**Comment by armaniferrante** [comment]
Yes both suggestions are desirable.

**Comment by AlirezaHamidiFayegh** [comment]
👍👍👍👍

**Pull request closed without merging**
