### PR TITLE
Add LUA Token and TOMO to popular tokens list

### PR DESCRIPTION
**Pull request by nghiatomo**

### CODE REVIEW

**Comment by thanhson1085** [comment]
Can you take a look our pull request @nishadsingh1 ?
We need it to listing TOMOE and LUA on Serum.
Thank you.

**Comment by nghiatomo** [comment]
@nishadsingh1 Can you help me to review this pull request, thanks in advance.

**Comment by nathanielparke** [comment]
Closing as these were added in 4c45341e3139b2f9764811fdbb1def2ec39d4f8f

**Comment by nathanielparke** [comment]
Icon was added here 604fa4b2937e6b1742f826c69a4ca4db3aa4b8e5 Thanks!

**Pull request closed without merging**
